const [GET_POKES, DELETE_POKE, CLEAR, GET_POKE_BY_ID, GET_TYPES, GET_POKE_BY_NAME, SORT_AZ, FILTER_TYPES, FILTER_DATA_SOURCE, SORT_ZA, FILTER_ATTACK] =
  ['GET_POKES', 'DELETE_POKE', 'CLEAR', 'GET_POKE_BY_ID', 'GET_TYPES', 'GET_POKE_BY_NAME', 'SORT_AZ', 'FILTER_TYPES', 'FILTER_DATA_SOURCE', 'SORT_ZA', 'FILTER_ATTACK']


export { GET_POKES, DELETE_POKE, CLEAR, GET_POKE_BY_ID, GET_TYPES, GET_POKE_BY_NAME, SORT_AZ, FILTER_TYPES, FILTER_DATA_SOURCE, SORT_ZA, FILTER_ATTACK }